@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.regutil.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;