@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault @FieldsAreNonnullByDefault @TypeUseAreNonnullByDefault
package tamaized.regutil.item;

import com.mojang.logging.annotations.FieldsAreNonnullByDefault;
import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import tamaized.regutil.TypeUseAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;