org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=true

# Mod Info
mod_id=regutil
mod_major_version=2.0
mod_version=0
group_name=tamaized.regutil

# Minecraft
minecraft_version=26.1.2

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.61-beta
mdg_version=2.0.141

# Deps
datagenutil_version=1.1.18
jei_version=28.0.0.6

